// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package dtos

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEbf570e8DecodeGithubComSkeswaEnbiyayBackendColorsDtos(in *jlexer.Lexer, out *TeamColorDetails) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "league":
			out.League = string(in.String())
		case "colors":
			easyjsonEbf570e8Decode(in, &out.Colors)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEbf570e8EncodeGithubComSkeswaEnbiyayBackendColorsDtos(out *jwriter.Writer, in TeamColorDetails) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"name\":")
	out.String(string(in.Name))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"league\":")
	out.String(string(in.League))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"colors\":")
	easyjsonEbf570e8Encode(out, in.Colors)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TeamColorDetails) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEbf570e8EncodeGithubComSkeswaEnbiyayBackendColorsDtos(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TeamColorDetails) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEbf570e8EncodeGithubComSkeswaEnbiyayBackendColorsDtos(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TeamColorDetails) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEbf570e8DecodeGithubComSkeswaEnbiyayBackendColorsDtos(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TeamColorDetails) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEbf570e8DecodeGithubComSkeswaEnbiyayBackendColorsDtos(l, v)
}
func easyjsonEbf570e8Decode(in *jlexer.Lexer, out *struct {
	Hex []string "json:\"hex\""
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "hex":
			if in.IsNull() {
				in.Skip()
				out.Hex = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					out.Hex = make([]string, 0, 4)
				} else {
					out.Hex = []string{}
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Hex = append(out.Hex, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEbf570e8Encode(out *jwriter.Writer, in struct {
	Hex []string "json:\"hex\""
}) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"hex\":")
	if in.Hex == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in.Hex {
			if v2 > 0 {
				out.RawByte(',')
			}
			out.String(string(v3))
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}
func easyjsonEbf570e8DecodeGithubComSkeswaEnbiyayBackendColorsDtos1(in *jlexer.Lexer, out *AllTeamColorDetails) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "teamColors":
			if in.IsNull() {
				in.Skip()
				out.TeamColors = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					out.TeamColors = make([]TeamColorDetails, 0, 1)
				} else {
					out.TeamColors = []TeamColorDetails{}
				}
				for !in.IsDelim(']') {
					var v4 TeamColorDetails
					(v4).UnmarshalEasyJSON(in)
					out.TeamColors = append(out.TeamColors, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEbf570e8EncodeGithubComSkeswaEnbiyayBackendColorsDtos1(out *jwriter.Writer, in AllTeamColorDetails) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"teamColors\":")
	if in.TeamColors == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in.TeamColors {
			if v5 > 0 {
				out.RawByte(',')
			}
			(v6).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AllTeamColorDetails) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEbf570e8EncodeGithubComSkeswaEnbiyayBackendColorsDtos1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AllTeamColorDetails) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEbf570e8EncodeGithubComSkeswaEnbiyayBackendColorsDtos1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AllTeamColorDetails) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEbf570e8DecodeGithubComSkeswaEnbiyayBackendColorsDtos1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AllTeamColorDetails) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEbf570e8DecodeGithubComSkeswaEnbiyayBackendColorsDtos1(l, v)
}
