apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
      - name: frontend
        image: us.gcr.io/courtblink/frontend:0.6.0